### ISSUE TITLE
Rename index Page not working

### ISSUE THREAD

**Issue by MysticalEnnio** [wobsoriano/nuxt-firebase-auth-starter#2]
When I rename the index page to login and then try to reach the Page it redicts to the index page...

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/nuxt-firebase-auth-starter/blob/master/plugins/middleware.global.ts#L6

**Comment by MysticalEnnio** [comment]
I tried that and its still not working... I have a link in my startpage that redicts to login, but login redicts me to the startpage. My middleware looks like this:
`export default defineNuxtPlugin(() => {
  const user = useUser()
  addRouteMiddleware(
    'auth',
    (to) => {
      if (to.path === '/login' && user.value)
        return navigateTo('/private')
    },
    { global: true },
  )
})
`

**Comment by MysticalEnnio** [comment]
I fixed it... Just had to clear the cache cause the old redicts were still in
