### ISSUE TITLE
Cannot read properties of undefined (reading 'tenantId')

### ISSUE THREAD

**Issue by davies-maina** [wobsoriano/nuxt-firebase-auth-starter#4]
Trying to sign in with email and password and getting the error on the title. Could it be an issue with my firebase setup? Kindly help

**Comment by wobsoriano** [comment]
Probably with your setup. I pushed an update, try it thanks

**Comment by davies-maina** [comment]
Yeah, I was invited to collaborate on a project on firebase and used the config for that project and that brings the error. I created a new firebase project and added it to your pushed code and it works perfectly. Thanks!
