### ISSUE TITLE
ESM Loader Issue & Auth Undefined

### ISSUE THREAD

**Issue by madeofcloud** [wobsoriano/nuxt-firebase-auth-starter#6]
I was getting errors in my project and cloned this repository to see if it was just my project throwing the errors. After cloning this repository, I got the same errors as in my original project. 

I am getting this error when I run this repository but only when experimental.viteNode is enabled:
```[nuxt] [request error] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'```

After I disable experimental.viteNode I get this error:
```[nuxt] [request error] Cannot read property 'Auth' of undefined```

**Comment by madeofcloud** [comment]
I have tried running the project on WSL and it works perfectly. From the information I found online, this is an issue only on Windows so I guess I will just have to continue using WSL for now.

**Comment by wobsoriano** [comment]
thanks. feel free to open again :)

**Comment by madeofcloud** [comment]
I think this issue was fixed with the Nuxt v3.0.0-rc.4 so it works fine now.
